### ISSUE TITLE
会导致部分内容的换行符无效

### ISSUE THREAD

**Issue by dcty** [viewweiwu/v2ex-zhihu-theme#2]
https://www.v2ex.com/t/856779#reply6
开启
![image](https://user-images.githubusercontent.com/792929/171423562-b979eedf-697a-4559-aebb-28b3bb23f5f7.png)
关闭
![image](https://user-images.githubusercontent.com/792929/171423641-758ecf04-e8d5-441c-b4dc-529bed15cf4e.png)

**Comment by viewweiwu** [comment]
好的，我看看怎么处理

**Comment by viewweiwu** [comment]
可以了，请使用 1.6.1 版本。
或者使用最后一个版本。
```css
@import "https://cdn.jsdelivr.net/gh/viewweiwu/v2ex-zhihu-theme@latest/v2ex.css";
```

保存后，强制刷新下页面就可以了。

**Comment by viewweiwu** [comment]
1.6.2 处理了间距问题
